name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"

      - name: Install required packages
        shell: bash -el {0}
        run: conda install -n base conda-build hatch -c conda-forge

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda list
        shell: bash -el {0}
        run: conda list

      - name: Run checks
        shell: base -el {0}
        run: hatch env run -e test check

      - name: Run tests
        shell: base -el {0}
        run: pytest -v
